server:
   port: 8080
   
management:
   port: 8081

spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: DB_EXP_TEST
   mvc:
      throw-exception-if-no-handler-found: true
   resources:
      add-mappings: false
         
info.app:
   encoding: @project.build.sourceEncoding@
   project.name: @project.name@
   project.version: @project.version@
   java.source: @java.version@
   java.target: @java.version@